### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by kkoci** [odoo-chile/l10n_cl_dte#6]
Hola, cómo están

Tengo éste error desde hace dias, cada vez que quiero enviar un xml y no he podido cerciorarme de que funciona, al dar click sobre "Send XML" Odoo me lanza éste error:

`TypeError: object of type 'bool' has no len()`

Tengo entendido que la clase es:

`class invoice(models.Model):`

Allí está el campo `sii_xml_request`

Es éste el que dá el problema, yo medio lo resolví con un condicional por si estaba vacío pero en otro lugar el logger, dá el error.

Ahora, ésta versión la descargué hace casi un mes, no sé si ya esté resuelto, estoy usando la versión para odoo 9 community.

En ésta parte se resolvió el problema con el condicional:

`_logger.info('len (como viene): %s' % len(self.sii_xml_request)if self.sii_xml_request else '')`

Pero luego, más abajo coloqué otro y nada, sigue con el mismo error:

`response = pool.urlopen('POST', url, headers={
            'Content-Type': 'application/soap+xml',
            'charset': 'utf-8',
            'Content-Length': (len(
                self.sii_xml_request) if self.sii_xml_request is not True or False else '')}, body=self.sii_xml_request)`

¿Alguna idea?

Por favor, es urgente, Gracias!

**Comment by kkoci** [comment]
Por si a las dudas, la descargué del branch 9.0, éso sí hace ya un mes.

Gracias

**Comment by Danisan** [comment]
Te recomiendo actualizar el código, ya que probablemente, si es código de un commit anterior, probablemente se haya resuelto el problema.
Cierro este issue, y si el error se repite en el nuevo desarrollo lo reabrimos.

**Comment by kkoci** [comment]
Ok, perfecto, voy a chequear el último entonces, cualquier cosa aviso, muchas gracias
