### ISSUE TITLE
ImportError: cannot import name masive_send_dte

### ISSUE THREAD

**Issue by kkoci** [odoo-chile/l10n_cl_dte#7]
Hola de nuevo,  buenas tardes, usando el último commit me dice que no puede importar el nombre

`masive_send_dte`

Verifiqué y efectivamente no existe en la carpeta, no logro instalarlo

Se me pasó algo?

Muchas Gracias

**Comment by Danisan** [comment]
Puedes precisar el error, desde el log?

**Comment by Danisan** [comment]
Estoy unificando archivos en la rama 9.0.. te pido por favor actualices nuevamente ahora. Gracias.

Estoy atento si surge cualquier inconveniente.

**Comment by kkoci** [comment]
Muchas Gracias Daniel, Ok, ahora actualizo y te informo, Gracias de nuevo

**Comment by kkoci** [comment]
Ya se resolvió éste problema, con el commit actualizado, muchas gracias!
